import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

const ICONS = {
  javascript: "js", typescript: "ts", php: "php", html5: "html", css3: "css", react: "react",
  "next.js": "nextjs", tailwind: "tailwind", bootstrap: "bootstrap", "node.js": "nodejs",
  laravel: "laravel", codeigniter: "codeigniter", git: "git", docker: "docker", figma: "figma",
  mysql: "mysql", postgresql: "postgres", mongodb: "mongodb", sqlite: "sqlite", postman: "postman", vscode: "vscode"
};

function renderTechIcons(stack) {
  const ids = stack.map((item) => ICONS[item.toLowerCase()]).filter(Boolean);
  return `<p align="center">\n  <img alt="Tech stack" src="https://skillicons.dev/icons?i=${ids.join(",")}&theme=dark&perline=9">\n</p>`;
}

function renderAboutCode(config) {
  const fence = "```";
  return [
    `${fence}js`,
    "const ronaldo = {",
    `  name: "${config.profile.name}",`,
    `  role: "${config.profile.headline}",`,
    `  from: "Kupang, NTT, Indonesia",`,
    `  education: "B.Sc. Computer Science, ${config.profile.affiliation} (2024)",`,
    `  currentlyBuilding: ["Satu Data NTT", "Dashboard Pimpinan"],`,
    `  currentlyLearning: "new frameworks & languages",`,
    `  askMeAbout: ["Web Dev", "APIs", "Databases", "anything tech"],`,
    "  reachMe: {",
    `    email: "ronaldlehot@gmail.com",`,
    `    instagram: "@ronaldlehot",`,
    "  },",
    "};",
    fence
  ].join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = config.techStack.map((item) => `\`${item}\``).join(" · ");
  const about = config.profile.about.join("\n\n");

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
${renderLinks(config.links)}
</p>

<p align="center">
  <img alt="Typing intro" src="https://readme-typing-svg.demolab.com?font=JetBrains+Mono&weight=600&size=18&pause=1200&color=22D3EE&center=true&vCenter=true&width=640&lines=${encodeURIComponent(config.profile.headline)}+from+${encodeURIComponent(config.profile.location)};Building+modern+%26+responsive+web+apps;I+debug+more+than+I+sleep">
</p>

## 👤 About Me

${renderAboutCode(config)}

## 👻 Contribution Pac-Man

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/${config.profile.username}/${config.profile.username}/output/pacman-contribution-graph-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/${config.profile.username}/${config.profile.username}/output/pacman-contribution-graph.svg">
    <img alt="Pac-Man eating my contribution graph" src="https://raw.githubusercontent.com/${config.profile.username}/${config.profile.username}/output/pacman-contribution-graph.svg" width="100%">
  </picture>
</p>
${activitySection}
---

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
