#!/usr/bin/env node

import { execFile } from "node:child_process";
import { access, readFile, readdir } from "node:fs/promises";
import { resolve } from "node:path";
import { promisify } from "node:util";
import { loadConfig, repositoryRoot } from "./lib/config.mjs";
import { ACTIVITY_END, ACTIVITY_START } from "./lib/readme.mjs";

const execFileAsync = promisify(execFile);

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

async function validateJavaScript() {
  const scriptDirectory = resolve(repositoryRoot, "scripts");
  const libDirectory = resolve(scriptDirectory, "lib");
  const files = [
    ...(await readdir(scriptDirectory)).filter((file) => file.endsWith(".mjs")).map((file) => resolve(scriptDirectory, file)),
    ...(await readdir(libDirectory)).filter((file) => file.endsWith(".mjs")).map((file) => resolve(libDirectory, file))
  ];
  for (const file of files) await execFileAsync(process.execPath, ["--check", file]);
  return files.length;
}

async function readManifest() {
  try {
    return JSON.parse(await readFile(resolve(repositoryRoot, "assets/hero/manifest.json"), "utf8"));
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

try {
  const config = await loadConfig();
  const scriptCount = await validateJavaScript();
  const readme = await readFile(resolve(repositoryRoot, "README.md"), "utf8");
  const manifest = await readManifest();

  if (manifest) {
    const assetNames = Object.values(manifest.assets || {});
    assert(assetNames.length === 4, "Hero manifest must contain four responsive theme assets.");
    for (const assetName of assetNames) {
      const assetPath = resolve(repositoryRoot, "assets/hero", assetName);
      await access(assetPath);
      const svg = await readFile(assetPath, "utf8");
      assert(svg.startsWith("<svg") && svg.endsWith("</svg>"), `${assetName} is not a complete SVG document.`);
      assert(!svg.includes("${"), `${assetName} contains an unresolved template expression.`);
      assert(readme.includes(assetName), `README.md does not reference ${assetName}.`);
    }
  }

  if (readme.includes("Generated by GitHub Profile Agent Console") && config.activity.enabled) {
    assert(readme.includes(ACTIVITY_START) && readme.includes(ACTIVITY_END), "Generated README is missing activity markers.");
  }

  console.log(`Validated profile configuration and ${scriptCount} JavaScript modules.`);
  console.log(manifest ? `Validated hero asset version ${manifest.version}.` : "Template mode: no generated profile assets yet.");
} catch (error) {
  console.error(`Validation failed: ${error.message}`);
  process.exitCode = 1;
}
